apiVersion: apps/v1
kind: Deployment
metadata:
  #name: nginx-deployment
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 9 # Update the replicas from 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - containerPort: 80
